blank_issues_enabled: true
contact_links:
  - name: Suggest changes you'd like to contribute
    url: https://github.com/Dynatrace/dynatrace-configuration-as-code-core/discussions/new?category=ideas
    about: Before you open a PR, we'd love to get a chance to discuss your proposed changes.
