name: Run Static Code Analysis

# This workflow uses golangci-lint to run static code analysis on PRs
# In addition to default golanci-linters checks vulnerability checks (gosec),
# closing of openend http bodies (bodyclose), cyclomatic complexity (cyclop),
# exhaustive switches (exhaustive) and open TODO/FIXME comments (godox)

on:
  pull_request:
    branches: [ main ]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: 🛠️ Set up Go 1.x
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 #v5.0.0
        with:
          go-version: '~1.22'

      - name: ⬇️ Check out code into the Go module directory
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 #v4.1.2

      - name: ✍️ Check format
        run: make lint

      - name: 🕵️ Go vet
        run: make vet

      - name: 🔎 golangci-lint
        uses: reviewdog/action-golangci-lint@f016e796a429b33094d0da6e86af3fa5479afe65 #v2.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
